package main.java;

public class DayTwo {
    private String plan = "forward 1\n" +
            "down 6\n" +
            "down 6\n" +
            "forward 2\n" +
            "forward 2\n" +
            "down 2\n" +
            "down 1\n" +
            "down 5\n" +
            "down 7\n" +
            "down 3\n" +
            "forward 1\n" +
            "forward 6\n" +
            "up 2\n" +
            "forward 2\n" +
            "forward 7\n" +
            "forward 4\n" +
            "down 2\n" +
            "forward 6\n" +
            "forward 6\n" +
            "down 3\n" +
            "up 7\n" +
            "down 6\n" +
            "forward 2\n" +
            "up 5\n" +
            "down 7\n" +
            "forward 8\n" +
            "down 8\n" +
            "forward 8\n" +
            "down 5\n" +
            "down 5\n" +
            "down 8\n" +
            "forward 9\n" +
            "down 7\n" +
            "forward 9\n" +
            "forward 9\n" +
            "forward 8\n" +
            "down 6\n" +
            "down 9\n" +
            "down 1\n" +
            "forward 8\n" +
            "down 6\n" +
            "down 7\n" +
            "up 3\n" +
            "forward 5\n" +
            "down 1\n" +
            "down 7\n" +
            "up 8\n" +
            "forward 6\n" +
            "down 2\n" +
            "down 9\n" +
            "down 9\n" +
            "forward 1\n" +
            "down 2\n" +
            "down 9\n" +
            "forward 1\n" +
            "forward 3\n" +
            "down 6\n" +
            "up 7\n" +
            "down 7\n" +
            "forward 3\n" +
            "down 4\n" +
            "down 3\n" +
            "up 7\n" +
            "up 7\n" +
            "forward 2\n" +
            "down 7\n" +
            "forward 2\n" +
            "down 3\n" +
            "up 7\n" +
            "down 7\n" +
            "forward 6\n" +
            "down 2\n" +
            "down 7\n" +
            "forward 5\n" +
            "down 9\n" +
            "down 2\n" +
            "up 7\n" +
            "down 1\n" +
            "forward 5\n" +
            "down 5\n" +
            "forward 9\n" +
            "down 6\n" +
            "down 3\n" +
            "down 7\n" +
            "down 8\n" +
            "down 3\n" +
            "up 4\n" +
            "down 6\n" +
            "forward 6\n" +
            "up 7\n" +
            "up 2\n" +
            "forward 3\n" +
            "up 1\n" +
            "down 5\n" +
            "forward 9\n" +
            "up 3\n" +
            "forward 8\n" +
            "up 4\n" +
            "down 7\n" +
            "down 8\n" +
            "down 3\n" +
            "down 7\n" +
            "forward 5\n" +
            "up 6\n" +
            "down 4\n" +
            "down 8\n" +
            "down 8\n" +
            "forward 7\n" +
            "down 5\n" +
            "forward 3\n" +
            "forward 1\n" +
            "down 1\n" +
            "forward 1\n" +
            "up 1\n" +
            "forward 4\n" +
            "forward 9\n" +
            "up 8\n" +
            "down 7\n" +
            "down 9\n" +
            "down 1\n" +
            "down 2\n" +
            "down 1\n" +
            "down 4\n" +
            "forward 4\n" +
            "forward 8\n" +
            "forward 6\n" +
            "forward 1\n" +
            "forward 6\n" +
            "forward 9\n" +
            "down 1\n" +
            "up 9\n" +
            "down 9\n" +
            "forward 2\n" +
            "down 6\n" +
            "down 8\n" +
            "down 6\n" +
            "up 7\n" +
            "forward 2\n" +
            "up 2\n" +
            "forward 5\n" +
            "down 2\n" +
            "up 2\n" +
            "up 9\n" +
            "forward 7\n" +
            "down 6\n" +
            "forward 3\n" +
            "down 5\n" +
            "up 4\n" +
            "down 1\n" +
            "down 5\n" +
            "down 6\n" +
            "up 7\n" +
            "down 3\n" +
            "down 9\n" +
            "up 8\n" +
            "down 2\n" +
            "up 8\n" +
            "down 1\n" +
            "down 2\n" +
            "down 4\n" +
            "forward 6\n" +
            "up 7\n" +
            "up 3\n" +
            "forward 8\n" +
            "down 9\n" +
            "down 8\n" +
            "forward 3\n" +
            "up 5\n" +
            "forward 1\n" +
            "down 5\n" +
            "up 2\n" +
            "down 5\n" +
            "up 4\n" +
            "down 6\n" +
            "forward 9\n" +
            "down 1\n" +
            "down 1\n" +
            "forward 1\n" +
            "down 2\n" +
            "forward 9\n" +
            "up 5\n" +
            "down 7\n" +
            "forward 7\n" +
            "down 9\n" +
            "down 5\n" +
            "down 3\n" +
            "forward 4\n" +
            "down 2\n" +
            "forward 7\n" +
            "forward 3\n" +
            "up 4\n" +
            "down 9\n" +
            "forward 9\n" +
            "forward 3\n" +
            "forward 1\n" +
            "forward 6\n" +
            "down 1\n" +
            "down 5\n" +
            "down 3\n" +
            "forward 9\n" +
            "down 2\n" +
            "forward 9\n" +
            "up 7\n" +
            "forward 7\n" +
            "forward 7\n" +
            "forward 8\n" +
            "forward 6\n" +
            "forward 5\n" +
            "down 7\n" +
            "up 4\n" +
            "forward 7\n" +
            "up 2\n" +
            "forward 6\n" +
            "down 2\n" +
            "down 9\n" +
            "down 3\n" +
            "forward 5\n" +
            "down 3\n" +
            "down 9\n" +
            "forward 2\n" +
            "up 4\n" +
            "forward 7\n" +
            "forward 3\n" +
            "forward 8\n" +
            "down 4\n" +
            "forward 4\n" +
            "down 3\n" +
            "up 7\n" +
            "up 1\n" +
            "up 4\n" +
            "down 3\n" +
            "down 5\n" +
            "down 3\n" +
            "down 7\n" +
            "down 3\n" +
            "down 7\n" +
            "down 5\n" +
            "down 1\n" +
            "forward 5\n" +
            "forward 6\n" +
            "down 1\n" +
            "forward 9\n" +
            "down 4\n" +
            "up 1\n" +
            "forward 5\n" +
            "up 6\n" +
            "down 4\n" +
            "up 7\n" +
            "down 4\n" +
            "down 9\n" +
            "forward 7\n" +
            "up 8\n" +
            "forward 3\n" +
            "forward 5\n" +
            "down 9\n" +
            "down 1\n" +
            "down 7\n" +
            "forward 9\n" +
            "down 9\n" +
            "down 5\n" +
            "forward 6\n" +
            "forward 4\n" +
            "forward 3\n" +
            "down 1\n" +
            "down 2\n" +
            "up 4\n" +
            "up 7\n" +
            "down 8\n" +
            "forward 4\n" +
            "forward 1\n" +
            "forward 8\n" +
            "down 8\n" +
            "down 8\n" +
            "forward 1\n" +
            "forward 5\n" +
            "up 8\n" +
            "forward 2\n" +
            "down 6\n" +
            "forward 6\n" +
            "down 6\n" +
            "forward 7\n" +
            "down 9\n" +
            "down 4\n" +
            "up 4\n" +
            "up 5\n" +
            "down 7\n" +
            "forward 4\n" +
            "down 7\n" +
            "down 5\n" +
            "forward 7\n" +
            "down 3\n" +
            "down 2\n" +
            "forward 5\n" +
            "forward 1\n" +
            "down 5\n" +
            "down 4\n" +
            "down 8\n" +
            "up 8\n" +
            "forward 3\n" +
            "down 7\n" +
            "down 8\n" +
            "down 5\n" +
            "forward 1\n" +
            "down 6\n" +
            "forward 8\n" +
            "forward 2\n" +
            "forward 3\n" +
            "down 4\n" +
            "up 3\n" +
            "down 4\n" +
            "forward 3\n" +
            "forward 9\n" +
            "up 5\n" +
            "up 9\n" +
            "down 3\n" +
            "up 4\n" +
            "forward 4\n" +
            "down 9\n" +
            "forward 8\n" +
            "down 2\n" +
            "down 2\n" +
            "forward 9\n" +
            "down 5\n" +
            "down 2\n" +
            "up 1\n" +
            "forward 6\n" +
            "forward 4\n" +
            "up 5\n" +
            "up 3\n" +
            "up 8\n" +
            "down 7\n" +
            "forward 5\n" +
            "up 7\n" +
            "forward 9\n" +
            "down 6\n" +
            "down 7\n" +
            "forward 4\n" +
            "down 9\n" +
            "up 2\n" +
            "forward 8\n" +
            "down 1\n" +
            "forward 6\n" +
            "forward 1\n" +
            "forward 4\n" +
            "down 9\n" +
            "down 6\n" +
            "up 1\n" +
            "forward 1\n" +
            "down 5\n" +
            "up 1\n" +
            "forward 3\n" +
            "down 1\n" +
            "down 4\n" +
            "forward 3\n" +
            "down 4\n" +
            "up 9\n" +
            "down 6\n" +
            "up 6\n" +
            "forward 1\n" +
            "forward 8\n" +
            "up 1\n" +
            "down 7\n" +
            "up 8\n" +
            "up 3\n" +
            "up 7\n" +
            "down 9\n" +
            "forward 8\n" +
            "down 3\n" +
            "up 2\n" +
            "forward 3\n" +
            "up 4\n" +
            "up 3\n" +
            "down 5\n" +
            "forward 3\n" +
            "forward 2\n" +
            "down 3\n" +
            "forward 5\n" +
            "up 4\n" +
            "down 9\n" +
            "down 8\n" +
            "down 3\n" +
            "down 5\n" +
            "down 7\n" +
            "forward 2\n" +
            "forward 8\n" +
            "up 9\n" +
            "forward 9\n" +
            "down 4\n" +
            "down 8\n" +
            "forward 5\n" +
            "down 2\n" +
            "up 4\n" +
            "down 7\n" +
            "forward 6\n" +
            "up 9\n" +
            "forward 6\n" +
            "down 9\n" +
            "down 5\n" +
            "forward 9\n" +
            "down 5\n" +
            "down 3\n" +
            "up 6\n" +
            "up 6\n" +
            "down 7\n" +
            "up 1\n" +
            "forward 7\n" +
            "forward 4\n" +
            "down 5\n" +
            "forward 8\n" +
            "down 5\n" +
            "down 8\n" +
            "forward 4\n" +
            "forward 8\n" +
            "forward 1\n" +
            "down 7\n" +
            "forward 4\n" +
            "down 6\n" +
            "down 4\n" +
            "up 8\n" +
            "down 4\n" +
            "up 5\n" +
            "up 7\n" +
            "up 2\n" +
            "down 5\n" +
            "down 9\n" +
            "forward 6\n" +
            "down 7\n" +
            "down 9\n" +
            "down 3\n" +
            "up 4\n" +
            "down 8\n" +
            "forward 3\n" +
            "forward 5\n" +
            "forward 8\n" +
            "down 9\n" +
            "forward 9\n" +
            "down 1\n" +
            "up 1\n" +
            "down 9\n" +
            "forward 3\n" +
            "up 9\n" +
            "forward 5\n" +
            "forward 2\n" +
            "down 1\n" +
            "down 5\n" +
            "down 6\n" +
            "forward 5\n" +
            "forward 4\n" +
            "up 5\n" +
            "forward 5\n" +
            "up 4\n" +
            "up 9\n" +
            "up 4\n" +
            "forward 8\n" +
            "down 7\n" +
            "down 6\n" +
            "down 9\n" +
            "down 3\n" +
            "down 2\n" +
            "down 6\n" +
            "up 6\n" +
            "forward 6\n" +
            "up 3\n" +
            "down 3\n" +
            "forward 3\n" +
            "down 2\n" +
            "down 9\n" +
            "down 3\n" +
            "forward 1\n" +
            "forward 8\n" +
            "down 2\n" +
            "down 9\n" +
            "down 6\n" +
            "up 3\n" +
            "down 6\n" +
            "forward 1\n" +
            "forward 1\n" +
            "forward 2\n" +
            "down 9\n" +
            "down 8\n" +
            "forward 9\n" +
            "down 2\n" +
            "up 3\n" +
            "forward 2\n" +
            "up 5\n" +
            "up 8\n" +
            "down 4\n" +
            "up 3\n" +
            "forward 3\n" +
            "forward 5\n" +
            "forward 1\n" +
            "down 5\n" +
            "up 4\n" +
            "forward 4\n" +
            "down 7\n" +
            "forward 8\n" +
            "up 7\n" +
            "forward 5\n" +
            "down 2\n" +
            "forward 4\n" +
            "forward 6\n" +
            "down 7\n" +
            "down 9\n" +
            "forward 2\n" +
            "forward 2\n" +
            "down 4\n" +
            "down 5\n" +
            "up 5\n" +
            "forward 5\n" +
            "forward 2\n" +
            "down 8\n" +
            "forward 6\n" +
            "down 1\n" +
            "down 6\n" +
            "forward 1\n" +
            "down 8\n" +
            "up 6\n" +
            "down 8\n" +
            "forward 4\n" +
            "down 4\n" +
            "down 4\n" +
            "forward 3\n" +
            "up 8\n" +
            "down 1\n" +
            "forward 7\n" +
            "down 5\n" +
            "forward 1\n" +
            "down 9\n" +
            "down 9\n" +
            "down 5\n" +
            "forward 1\n" +
            "down 4\n" +
            "up 6\n" +
            "forward 4\n" +
            "forward 5\n" +
            "forward 1\n" +
            "down 4\n" +
            "down 2\n" +
            "down 5\n" +
            "forward 6\n" +
            "forward 1\n" +
            "forward 6\n" +
            "down 2\n" +
            "down 6\n" +
            "forward 3\n" +
            "down 9\n" +
            "up 6\n" +
            "forward 2\n" +
            "up 7\n" +
            "forward 8\n" +
            "down 7\n" +
            "up 1\n" +
            "forward 1\n" +
            "down 8\n" +
            "forward 8\n" +
            "down 9\n" +
            "forward 4\n" +
            "down 4\n" +
            "down 5\n" +
            "down 8\n" +
            "up 3\n" +
            "forward 1\n" +
            "forward 9\n" +
            "down 9\n" +
            "up 2\n" +
            "down 1\n" +
            "down 8\n" +
            "down 6\n" +
            "forward 3\n" +
            "down 8\n" +
            "down 3\n" +
            "forward 5\n" +
            "forward 2\n" +
            "forward 5\n" +
            "forward 5\n" +
            "forward 2\n" +
            "forward 4\n" +
            "down 9\n" +
            "down 3\n" +
            "forward 7\n" +
            "forward 3\n" +
            "up 3\n" +
            "up 1\n" +
            "forward 2\n" +
            "down 5\n" +
            "forward 3\n" +
            "up 3\n" +
            "forward 2\n" +
            "forward 9\n" +
            "forward 5\n" +
            "down 3\n" +
            "forward 9\n" +
            "up 2\n" +
            "forward 7\n" +
            "up 3\n" +
            "down 8\n" +
            "forward 7\n" +
            "up 5\n" +
            "forward 3\n" +
            "forward 4\n" +
            "up 5\n" +
            "down 6\n" +
            "up 2\n" +
            "forward 8\n" +
            "up 3\n" +
            "down 5\n" +
            "down 4\n" +
            "forward 9\n" +
            "up 2\n" +
            "down 5\n" +
            "forward 4\n" +
            "up 7\n" +
            "down 9\n" +
            "up 8\n" +
            "down 4\n" +
            "up 5\n" +
            "forward 4\n" +
            "down 8\n" +
            "forward 3\n" +
            "down 5\n" +
            "down 5\n" +
            "down 8\n" +
            "up 9\n" +
            "forward 3\n" +
            "forward 9\n" +
            "down 2\n" +
            "forward 4\n" +
            "down 1\n" +
            "up 3\n" +
            "down 9\n" +
            "up 6\n" +
            "down 1\n" +
            "down 1\n" +
            "down 5\n" +
            "down 1\n" +
            "down 7\n" +
            "forward 4\n" +
            "down 4\n" +
            "down 9\n" +
            "up 1\n" +
            "up 7\n" +
            "up 2\n" +
            "down 8\n" +
            "up 5\n" +
            "down 6\n" +
            "forward 6\n" +
            "forward 6\n" +
            "down 4\n" +
            "forward 9\n" +
            "forward 4\n" +
            "forward 9\n" +
            "forward 4\n" +
            "up 5\n" +
            "forward 9\n" +
            "up 7\n" +
            "up 1\n" +
            "forward 5\n" +
            "forward 9\n" +
            "down 7\n" +
            "forward 7\n" +
            "forward 6\n" +
            "down 5\n" +
            "forward 9\n" +
            "up 9\n" +
            "down 4\n" +
            "down 9\n" +
            "down 2\n" +
            "forward 3\n" +
            "down 3\n" +
            "down 3\n" +
            "forward 9\n" +
            "down 8\n" +
            "down 4\n" +
            "down 8\n" +
            "down 6\n" +
            "down 6\n" +
            "down 9\n" +
            "up 5\n" +
            "down 3\n" +
            "down 4\n" +
            "up 6\n" +
            "up 2\n" +
            "forward 1\n" +
            "up 9\n" +
            "up 9\n" +
            "forward 9\n" +
            "forward 7\n" +
            "down 3\n" +
            "forward 2\n" +
            "up 5\n" +
            "down 2\n" +
            "forward 2\n" +
            "forward 8\n" +
            "down 8\n" +
            "forward 4\n" +
            "forward 2\n" +
            "up 3\n" +
            "up 8\n" +
            "down 5\n" +
            "forward 5\n" +
            "forward 8\n" +
            "down 1\n" +
            "down 8\n" +
            "forward 3\n" +
            "forward 9\n" +
            "down 7\n" +
            "forward 5\n" +
            "forward 8\n" +
            "forward 1\n" +
            "up 6\n" +
            "forward 9\n" +
            "up 5\n" +
            "forward 8\n" +
            "forward 3\n" +
            "down 2\n" +
            "up 9\n" +
            "up 7\n" +
            "forward 5\n" +
            "down 8\n" +
            "down 3\n" +
            "forward 8\n" +
            "down 3\n" +
            "down 9\n" +
            "down 9\n" +
            "forward 7\n" +
            "down 9\n" +
            "forward 5\n" +
            "forward 1\n" +
            "forward 5\n" +
            "down 2\n" +
            "down 7\n" +
            "forward 4\n" +
            "down 4\n" +
            "up 8\n" +
            "down 2\n" +
            "up 1\n" +
            "down 1\n" +
            "up 5\n" +
            "up 6\n" +
            "down 5\n" +
            "up 9\n" +
            "up 6\n" +
            "down 6\n" +
            "down 4\n" +
            "down 3\n" +
            "forward 9\n" +
            "forward 2\n" +
            "forward 2\n" +
            "up 6\n" +
            "forward 9\n" +
            "down 3\n" +
            "forward 4\n" +
            "forward 6\n" +
            "forward 8\n" +
            "forward 2\n" +
            "forward 8\n" +
            "forward 4\n" +
            "down 1\n" +
            "forward 3\n" +
            "up 1\n" +
            "up 9\n" +
            "forward 9\n" +
            "up 6\n" +
            "up 5\n" +
            "forward 2\n" +
            "down 6\n" +
            "up 8\n" +
            "up 9\n" +
            "forward 3\n" +
            "forward 9\n" +
            "down 7\n" +
            "down 6\n" +
            "forward 2\n" +
            "down 7\n" +
            "forward 4\n" +
            "down 5\n" +
            "down 2\n" +
            "down 6\n" +
            "down 2\n" +
            "down 5\n" +
            "down 3\n" +
            "forward 3\n" +
            "down 7\n" +
            "down 6\n" +
            "down 5\n" +
            "up 2\n" +
            "forward 4\n" +
            "up 9\n" +
            "forward 2\n" +
            "forward 4\n" +
            "down 5\n" +
            "up 9\n" +
            "up 2\n" +
            "forward 9\n" +
            "forward 6\n" +
            "down 6\n" +
            "down 3\n" +
            "down 5\n" +
            "down 1\n" +
            "up 4\n" +
            "up 1\n" +
            "down 4\n" +
            "down 1\n" +
            "forward 5\n" +
            "forward 3\n" +
            "down 7\n" +
            "down 9\n" +
            "forward 2\n" +
            "down 3\n" +
            "up 7\n" +
            "down 2\n" +
            "down 6\n" +
            "forward 3\n" +
            "forward 3\n" +
            "down 3\n" +
            "up 1\n" +
            "forward 6\n" +
            "forward 3\n" +
            "down 6\n" +
            "down 2\n" +
            "up 4\n" +
            "up 3\n" +
            "down 5\n" +
            "down 9\n" +
            "down 3\n" +
            "forward 7\n" +
            "forward 2\n" +
            "forward 9\n" +
            "down 6\n" +
            "forward 4\n" +
            "up 9\n" +
            "forward 1\n" +
            "down 4\n" +
            "down 6\n" +
            "down 2\n" +
            "forward 3\n" +
            "down 2\n" +
            "up 8\n" +
            "forward 1\n" +
            "forward 9\n" +
            "down 9\n" +
            "up 7\n" +
            "forward 6\n" +
            "up 8\n" +
            "down 9\n" +
            "down 4\n" +
            "forward 8\n" +
            "down 6\n" +
            "down 1\n" +
            "down 9\n" +
            "down 1\n" +
            "up 7\n" +
            "forward 9\n" +
            "up 3\n" +
            "forward 7\n" +
            "up 7\n" +
            "down 2\n" +
            "forward 1\n" +
            "down 4\n" +
            "down 7\n" +
            "forward 7\n" +
            "forward 9\n" +
            "down 6\n" +
            "down 5\n" +
            "down 8\n" +
            "down 9\n" +
            "up 3\n" +
            "down 7\n" +
            "up 3\n" +
            "down 1\n" +
            "forward 1\n" +
            "forward 6\n" +
            "forward 2\n" +
            "down 6\n" +
            "forward 9\n" +
            "forward 1\n" +
            "up 2\n" +
            "forward 1\n" +
            "forward 3\n" +
            "forward 4\n" +
            "forward 7\n" +
            "forward 4\n" +
            "down 3\n" +
            "up 8\n" +
            "forward 9\n" +
            "down 7\n" +
            "forward 6\n" +
            "forward 3\n" +
            "down 6\n" +
            "forward 4\n" +
            "up 1\n" +
            "forward 3\n" +
            "down 3\n" +
            "forward 9\n" +
            "forward 2\n" +
            "forward 1\n" +
            "forward 4\n" +
            "up 6\n" +
            "forward 3\n" +
            "down 6\n" +
            "down 8\n" +
            "up 4\n" +
            "forward 8\n" +
            "forward 4\n" +
            "down 8\n" +
            "up 4\n" +
            "up 3\n" +
            "forward 9\n" +
            "forward 3\n" +
            "down 5\n" +
            "forward 7\n" +
            "forward 1\n" +
            "up 8\n" +
            "up 4\n" +
            "down 1\n" +
            "down 3\n" +
            "down 9\n" +
            "down 7\n" +
            "up 5\n" +
            "forward 6\n" +
            "down 1\n" +
            "forward 3\n" +
            "down 2\n" +
            "down 2\n" +
            "down 6\n" +
            "forward 2\n" +
            "down 5\n" +
            "forward 2\n" +
            "forward 1\n" +
            "up 9\n" +
            "down 1\n" +
            "forward 3\n" +
            "down 3\n" +
            "forward 6\n" +
            "down 1\n" +
            "forward 5\n" +
            "forward 7\n" +
            "down 6\n" +
            "forward 7\n" +
            "down 4\n" +
            "up 7\n" +
            "forward 1\n" +
            "down 7\n" +
            "down 8\n" +
            "down 9\n" +
            "down 6\n" +
            "down 1\n" +
            "forward 6\n" +
            "down 7\n" +
            "forward 2\n" +
            "down 2\n" +
            "up 1\n" +
            "up 2\n" +
            "down 3\n" +
            "down 4\n" +
            "up 2\n" +
            "forward 3\n" +
            "down 5\n" +
            "down 4\n" +
            "down 9\n" +
            "down 6\n" +
            "down 9\n" +
            "down 7\n" +
            "down 2\n" +
            "forward 7\n" +
            "forward 3\n" +
            "up 3\n" +
            "down 1\n" +
            "down 5\n" +
            "down 1\n" +
            "down 3\n" +
            "down 3\n" +
            "forward 9\n" +
            "down 1\n" +
            "down 7\n" +
            "up 4\n" +
            "down 1\n" +
            "down 6\n" +
            "up 9\n" +
            "down 9\n" +
            "forward 6\n" +
            "down 9\n" +
            "forward 3\n" +
            "forward 8\n" +
            "up 1\n" +
            "forward 3\n" +
            "down 8\n" +
            "forward 2\n" +
            "down 6\n" +
            "down 1\n" +
            "up 7\n" +
            "down 1\n" +
            "forward 3\n" +
            "down 2\n" +
            "forward 1\n" +
            "up 8\n" +
            "forward 8\n" +
            "forward 7\n" +
            "down 9\n" +
            "forward 3";

    public void run() {
        System.out.println("========================");
        System.out.println("Day 2 running...");
        System.out.println("========================");

        calculatePosition();
        calculatePositionWithAim();
    }

    private void calculatePosition() {
        System.out.println("Part One");
        System.out.println("Start calculating horizontal position and depth...");
        int[] result = new int[2];

        // cut string into movement parts, e.g. ["forward 1", "down 2", ...]
        String[] movements = plan.split("\n");
        for (String movement : movements) {
            // e.g. "forward 1" -> ["forward", "1"]
            String[] splitted = movement.split("\\s+");
            switch (splitted[0]) {
                case "up":
                    result[1] = result[1] - Integer.parseInt(splitted[1]);
                    break;
                case "down":
                    result[1] = result[1] + Integer.parseInt(splitted[1]);
                    break;
                case "forward":
                    result[0] = result[0] + Integer.parseInt(splitted[1]);
                    break;
                default:
                    throw new IllegalStateException();
            }
        }

        System.out.printf("horizontal position: %d and depth: %d%n", result[0], result[1]);
        System.out.println("Result Part One: " + result[0] * result[1]);
        System.out.println("-----------------------");
    }

   private void calculatePositionWithAim() {
       System.out.println("Part Two");
       System.out.println("Start calculating position with aim...");

       // [horizontal, depth, aim]
        int[] result = new int[3];
        String[] movements = plan.split("\n");

        for (String movement : movements) {
            String[] splitted = movement.split("\\s+");

            switch (splitted[0]) {
                case "up":
                    result[2] = result[2] - Integer.parseInt(splitted[1]);
                    break;
                case "down":
                    result[2] = result[2] + Integer.parseInt(splitted[1]);
                    break;
                case "forward":
                    result[0] = result[0] + Integer.parseInt(splitted[1]);
                    result[1] = result[1] + result[2] * Integer.parseInt(splitted[1]);
                    break;
                default:
                    throw new IllegalStateException();
            }
        }
       System.out.printf("horizontal position: %d and depth: %d and aim: %d%n", result[0], result[1], result[2]);
       System.out.println("Result Part Two: " + result[0] * result[1]);
    }
}
